/** Chinese display helpers for evaluation artifacts while preserving raw values in APIs. */

const LABELS: Record<string, string> = {
  preflight: '运行前检查',
  baseline: '基线评测',
  shadow: '影子评测',
  calibration: '指标校准',
  queued: '等待执行',
  running: '执行中',
  completed: '已完成',
  pending_approval: '待独立审批',
  approved: '已批准，待晋级',
  rejected: '已驳回',
  promoted: '已晋级',
  succeeded: '成功',
  failed: '失败',
  incomplete: '未完成',
  invalid_provenance: '溯源无效',
  skipped: '已跳过',
  not_applicable: '不适用',
  measured_pending_calibration: '已测量，等待校准',
  pending_calibration: '等待校准',
  smoke_only: '冒烟评测',
  off: '关闭证据门',
  shadow_mode: '影子模式',
  dense: '向量检索',
  vector: '向量检索',
  hybrid: '混合检索',
  dense_graph: '向量 + 图谱检索',
  dense_bm25: '向量 + 关键词检索',
  dense_bm25_graph: '向量 + 关键词 + 图谱检索',
  faithfulness: '忠实度',
  factual_correctness: '事实正确性',
  context_precision: '上下文精确率',
  context_recall: '上下文召回率',
  answer_relevancy: '回答相关性',
  semantic_similarity: '语义相似度',
  noise_sensitivity: '噪声敏感度',
  rubrics_score_with_reference: '参考答案 Rubric 评分',
  rubrics_score_without_reference: '安全与行为 Rubric 评分',
  evidence_gate_contract: '正式行为契约',
  retrieval: '检索',
  routing: '路由',
  answer: '回答',
  safety: '安全',
  qualification_or_routing: '证据判定或路由',
  fusion_or_candidate_selection: '融合或候选选择',
  dense_recall: '向量召回',
  generation: '生成',
  total: '样本总数',
  completed_count: '已完成',
  succeeded_count: '成功',
  failed_count: '失败',
  invalid_provenance_count: '溯源无效',
  id_scored: '可按 ID 评分',
  provenance_completeness: '溯源完整率',
  id_based_context_precision: '基于 ID 的上下文精确率',
  id_based_context_recall: '基于 ID 的上下文召回率',
  p50: 'P50 端到端回答延迟（毫秒）',
  p95: 'P95 端到端回答延迟（毫秒）',
  answerable_false_refusal_rate: '可回答问题误拒答率',
  claim_citation_coverage: '主张引用覆盖率',
  conflict_recognition_rate: '冲突识别率',
  groundedness_pass_rate: '依据充分通过率',
  no_answer_hallucination_rate: '无答案场景幻觉率',
  partial_answer_recognition_rate: '部分回答识别率',
  refusal_precision: '拒答精确率',
  refusal_recall: '拒答召回率',
  answer_routes: '回答路径数',
  citation_uses: '引用使用数',
  expected_answerable: '预期可回答数',
  expected_conflict: '预期冲突数',
  expected_no_answer: '预期不可回答数',
  expected_partial: '预期部分回答数',
  material_claims: '关键主张数',
  gate_mode: '离线证据门',
  run_id: '运行编号',
  calibration_version: '校准版本',
  acceptance_version: '验收规则版本',
  manifest_sha256: '清单指纹',
  baseline_template_sha256: '基线模板指纹',
  fixture_profile_sha256: 'Fixture 指纹',
  quality_report_sha256: '质量报告指纹',
  calibration_record_sha256: '校准记录指纹',
  evaluation_dataset_id: '正式评测集',
  evaluation_version: '正式评测版本',
  evaluation_manifest_sha256: '正式评测清单指纹',
  evaluation_case_count: '正式样本数',
  ragas_outcomes_sha256: 'RAGAS 逐题结果指纹',
  ragas_summary_sha256: 'RAGAS 汇总指纹',
  ragas_judge_source: '本次 RAGAS 评分来源',
  ragas_judge_model: '本次 RAGAS 评分模型',
  ragas_faithfulness: 'RAGAS 忠实度',
  ragas_factual_correctness: 'RAGAS 事实正确性',
  ragas_context_quality: 'RAGAS 上下文质量',
  finance: '财务',
  hr: '人事',
  human_resources: '人事',
  procurement: '采购',
  sales: '销售',
  legal: '法务',
  engineering: '研发',
  administration: '行政',
  security: '安全',
  answerable: '可回答',
  conflict: '冲突',
  no_answer: '无答案',
  partial: '部分回答',
  prompt_injection: '提示词注入',
  all_branches_unavailable: '全部检索分支不可用',
  authorization_filtered: '权限过滤',
  background_only: '仅背景信息',
  completely_unanswerable: '完全不可回答',
  conflicting: '证据冲突',
  fully_answerable: '完全可回答',
  missing_business_record: '缺少业务记录',
  missing_version_or_date: '缺少版本或日期',
  partially_answerable: '部分可回答',
  single_branch_unavailable: '单个检索分支不可用',
  category_metrics: '类别专项指标',
  exact_evidence_retrieval: '精确证据召回',
  response_route_correctness: '回答路由正确率',
  citation_correctness: '引用正确性',
  grounding_correctness: '依据充分正确率',
  partial_recognition: '部分回答识别率',
  supported_part_coverage: '已支持部分覆盖率',
  unsupported_claim_rate: '无依据主张率',
  missing_information_accuracy: '缺失信息识别准确率',
  conflict_recognition: '冲突识别率',
  opposing_evidence_coverage: '对立证据覆盖率',
  unsupported_resolution_rate: '无依据裁决率',
  background_classification: '背景信息识别率',
  correct_non_answer_route: '正确非回答路由率',
  unsupported_answer_rate: '无依据作答率',
  clarification_route: '澄清路由率',
  missing_slot_accuracy: '缺失槽位准确率',
  missing_record_route: '缺记录路由率',
  missing_field_accuracy: '缺失字段准确率',
  zero_results_route: '零结果路由率',
  refusal_correctness: '拒答正确率',
  hallucination_rate: '幻觉率',
  authorization_route: '权限过滤路由率',
  unauthorized_citation_rate: '未授权引用率',
  cross_scope_leakage_rate: '跨权限泄漏率',
  partial_outage_recognition: '部分故障识别率',
  answer_continuity: '故障下回答连续性',
  remaining_branch_retrieval_quality: '剩余分支检索质量',
  source_unavailable_route: '来源不可用路由率',
  branch_state_accuracy: '分支状态准确率',
  injection_detection: '提示词注入识别率',
  human_review_route: '人工复核路由率',
  instruction_data_leakage_rate: '指令数据泄漏率',
  prompt_injection_detected: '已检测到提示词注入',
}

const REASON_LABELS: Record<string, string> = {
  ragas_configuration_missing: 'RAGAS 评分器未配置：请检查评测 Judge 的密钥、模型和服务地址。',
  ragas_evaluation_failed: 'RAGAS 评分器执行失败：该历史运行没有保留底层错误类型，请查看 Worker 日志后重试。',
  ragas_evaluator_initialization_failed: 'RAGAS 评分器初始化失败：评测模型适配器与当前 RAGAS 指标不兼容，请部署兼容修复后重试。',
  ragas_execution_timeout: 'RAGAS 评分超过 Worker 的执行时间上限：已保留已完成的评分，可直接重试以继续剩余项目。',
  ragas_temporary_storage_full: 'RAGAS 评分失败：Worker 临时存储空间不足，请释放磁盘或临时目录空间后重试。',
  ragas_judge_timeout: 'RAGAS 评分超时：评测模型服务未在规定时间内返回，请检查服务负载后重试。',
  ragas_judge_unavailable: 'RAGAS 评分器不可用：无法连接评测模型服务，请检查网络和服务状态。',
  ragas_judge_auth_failed: 'RAGAS 评分器认证失败：请检查评测模型凭据。',
  ragas_judge_rate_limited: 'RAGAS 评分被限流：请稍后重试或调整评测服务配额。',
  ragas_judge_request_rejected: 'RAGAS 评分请求被评测模型拒绝：请检查模型兼容性与请求限制。',
  ragas_responses_missing: 'RAGAS 评分输入缺失：未找到本次运行的问答结果。',
  ragas_responses_invalid: 'RAGAS 评分输入无效：冻结问答快照格式不完整。',
  ragas_input_preparation_failed: 'RAGAS 评分输入准备失败：Worker 已记录安全诊断信息，请检查日志后重试。',
  ragas_reference_evidence_invalid: 'RAGAS 参考证据无效：正式评测清单与已审核证据摘要不一致，请修复评测集后重试。',
  ragas_reference_missing: 'RAGAS 评分输入缺少冻结参考答案：请重新生成或修复正式评测数据集。',
  ragas_summary_missing: 'RAGAS 评分汇总缺失：逐题评分未能生成完整汇总。',
  ragas_summary_invalid: 'RAGAS 评分汇总格式无效：请检查评测 Worker 日志。',
  ragas_outcomes_invalid: 'RAGAS 逐题评分结果格式无效：请检查评测 Worker 日志后重试。',
  formal_qa_snapshot_incomplete: '正式问答快照不完整：存在执行失败或无效溯源，系统已停止 RAGAS 评分；请直接重试问答阶段。',
  release_self_approval_forbidden: '发起人不能审批或驳回自己发起的发布。',
  release_checker_unavailable: '至少需要两名启用的组织管理员才能完成独立审批。',
  release_not_approved: '工作流尚未获得有效独立审批。',
  gate_transition_invalid: 'Gate 只能按关闭→影子→强制执行逐级晋级。',
  gate_no_prior_configuration: '当前没有可回滚的持久化 Gate 配置。',
  gate_history_missing: 'Gate 历史不完整，不能安全回滚。',
  gate_revision_conflict: 'Gate 配置已更新，请刷新后重试。',
  calibration_source_unbound: '校准来源未绑定报告与响应快照哈希。',
  calibration_source_report_incomplete: '校准来源包含失败、溯源无效或冒烟级报告。',
  calibration_source_incomparable: '基线与影子评测的冻结身份不可比。',
  ragas_coverage_incomplete: 'RAGAS 覆盖不完整：冻结评测集与逐题评分数量不一致，请直接重试以续跑缺失项目。',
  ragas_required_score_failed: 'RAGAS 必需评分未完成：存在评分失败的样本（通常是裁判模型偶发故障）。点击"重试"只需重跑失败样本；可在运行详情的异常抽检面板查看具体失败的指标。',
  ragas_coverage_contains_skips: 'RAGAS 正式覆盖包含旧式跳过结果：请用新规则重试，所有正式用例都必须有评分或明确的不适用终态。',
  evidence_gate_contract_incomplete: '正式行为契约覆盖不完整：每个冻结用例都必须有可审核的行为契约评分。',
  formal_reviewed_contract_invalid: '已批准样本的类别、预期路由或证据绑定不一致，已在调用 Judge 前阻断。',
  formal_runtime_evidence_mismatch: '冻结金标证据与本次运行时语料或切块不一致，已在调用 Judge 前阻断。',
  formal_runtime_evidence_invalid: '冻结金标证据身份无效，无法安全执行正式评测。',
  ragas_coverage_unscored: 'RAGAS 没有产生有效评分：请检查跳过原因与评测输入完整性。',
  record_not_evaluable: '问答执行未成功，无法进行该项评分',
  missing_question: '缺少评测问题',
  missing_response: '缺少回答内容',
  missing_reference: '缺少可用于该指标的审核参考证据',
  missing_retrieved_contexts: '缺少可评分的检索上下文',
  audited_no_evidence_route: '已审核的无证据/拒答路径，不适用于该 RAGAS 指标',
  audited_no_answer_route: '已审核且正确执行的无答案/拒答路径，不适用于事实正确性',
  audited_retrieval_unavailable_route: '已审核的检索不可用路径，不适用于该 RAGAS 指标',
  evaluation_stage_disabled: '本次对照模式未执行该指标依赖的生成或依据校验阶段',
  judge_exception: '评分器调用异常',
  judge_timeout: '评分模型请求超时',
  judge_unavailable: '评分模型服务不可用',
  judge_auth_failed: '评分模型认证失败',
  judge_rate_limited: '评分模型服务限流',
  judge_structured_output_retry_exhausted: '评分模型未能返回 RAGAS 所需的结构化结果',
  judge_json_object_invalid: '评分模型返回的 JSON 对象不符合评分结构',
  InstructorRetryException: 'Instructor 结构化校验重试耗尽',
  IncompleteOutputException: '结构化输出未完成',
  RagasJudgeJsonObjectError: '评分 JSON 对象无法通过本地校验',
  stop: '正常结束',
  length: '达到输出长度上限',
  content_filter: '内容过滤结束',
  judge_invalid_score: '评分器返回了无效分数',
  release_output_not_writable: '评测结果目录不可写：请检查 Worker 的结果卷与磁盘空间。',
  runtime_preflight_blocked: '运行前检查未通过：请展开工作流查看该阶段详情。',
  orphaned_worker_attempt: 'Worker 执行中断：该尝试已被安全关闭，可创建新尝试重试。',
  calibration_metrics_incomplete: '校准指标不完整：基线或影子评测缺少校准所需的指标。',
  smoke_only_calibration_not_required: '冒烟测试无需执行指标校准；基线和影子评测结果已保留。',
  smoke_acceptance_source_invalid: '冒烟验收失败：基线或影子评测来源身份不完整。',
  smoke_acceptance_contract_mismatch: '冒烟验收失败：存在预期路由不匹配，不能进入审批或 Gate 晋级。',
  smoke_acceptance_reference_missing: '冒烟验收失败：可回答样本缺少已审核参考答案，关键质量指标未实际执行。',
  smoke_acceptance_hard_gate: '冒烟验收失败：存在安全、权限或溯源硬门。',
  reranker_support: '重排模型对该证据提供了额外支持。',
  quality_report_missing: '质量报告缺失：该阶段没有生成可用于后续处理的报告。',
  fixture_runtime_corpus_unaligned: '当前语料与冻结评测集不一致：请重新对齐后再运行。',
  paused_by_admin: '管理员已暂停该评测；已有基线结果已保留，影子阶段未继续执行。',
}

/** Return a Chinese label for a known evaluation field while keeping unknown keys legible. */
export function evaluationLabel(value: string | null | undefined): string {
  if (!value) return '—'
  return LABELS[value] ?? value
}

/** Render a stable workflow reason code as a Chinese explanation. */
export function evaluationReasonLabel(value: string | null | undefined): string {
  if (!value) return '—'
  const ordinaryAnswerPrefix = 'ordinary_answer_metric_invalid_for_'
  if (value.startsWith(ordinaryAnswerPrefix)) {
    const category = value.slice(ordinaryAnswerPrefix.length)
    return `${evaluationLabel(category)}题型按评测策略不适用普通答案指标`
  }
  return REASON_LABELS[value] ?? `未映射原因：${value}`
}

/** Translate a raw status without changing its API value. */
export function evaluationStatusLabel(value: string | null | undefined): string {
  return evaluationLabel(value)
}

/** Format scalars safely for compact report tables. */
export function formatEvaluationValue(value: unknown): string | number {
  if (value === null || value === undefined) return '—'
  if (typeof value === 'number') return value
  if (typeof value === 'boolean') return value ? '是' : '否'
  if (typeof value === 'string') return evaluationLabel(value)
  return '—'
}
